server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: prometheus, health, metrics
  metrics:
    tags:
      service: websocket-service

spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: websocket-service
