server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: prometheus, health, metrics
  metrics:
    tags:
      service: stream-processor

spring:
  kafka:
    bootstrap-servers: localhost:9092
    streams:
      application-id: stream-processor
      properties:
        default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
        default.value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
  data:
    redis:
      host: localhost
      port: 6379

app:
  window:
    duration-seconds: 300
